### ISSUE TITLE
Newer Game Version

### ISSUE THREAD

**Issue by woodman231** [southpawgeek/monster-sanctuary-data#8]
Hello,

This is pretty cool. When I launch the game it says that the version is 2.0.0.60. Your README says that this data is as of 1.3.0.18. Will a newer version of the data be available soon?

Thanks,
Sean W.

**Comment by southpawgeek** [comment]
Hi Sean,

I started parsing the data in a new branch shortly after the DLC came out, but never finished working on it. I am not sure if/when I'll continue, because I haven't played Monster Sanctuary in a while.

I'm not confident in the quality of the data, which is why I never moved it out of the branch. But, feel free to take a look!

https://github.com/southpawgeek/monster-sanctuary-data/tree/game-update-2.0

**Comment by woodman231** [comment]
That is pretty cool. It does look like the newer things are producing nulls, such as the materials like gold, or monster types that are ancient.

**Comment by woodman231** [comment]
For what it is worth I created a BepInEx plugin to extract the game data that I wanted. You can check it out if you want.

https://github.com/woodman231/AddAndExportAllMonsters

**Comment by southpawgeek** [comment]
@woodman231 great work! I'll have to check that out. Pulling data in-game looks like it circumvents some of the weirdness I encountered - for example I wasn't able to locate weakness/resistance information in the monster prefabs (or I was unable to recognize it).

Thanks for the update!

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
shinjjune, @bradford-hamilton, @loyalcanadait, @Aniket21mathur, @cole67, @Phoenix6960, @kajumito, @c0r1y-6a0, @felipsoarez, @TekEffekt, @richardsmet, @rharari, @Alekhyadaspet, @kevinxiong, @nanmu42, @Eddievin, @devshansharma, @CharlesCreativeContent, @yojeajie, @jallynme, @kkpsiren, @trampboy, @feiw24, @Kavitharavih, @kvzn, @MostafaMhmod, @robrovi, @lee1221ee, @fmunoz92, @warrichrepos, @bsdfzzzy, @zyp001a, @faliwang, @mirismaili, @itmustbejj, @MarlenAw, @ghiblin, @nodc, @Crazycamp, @vgchl, @kevinbluer, @justdo86, @coinrule-token, @rjoshima, @neuralbayes, @ufukomer, @imnisen, @huzhengen, @Ractive89, @shanefontainepol3et, @themartorana, @sujayxaradhya, @askender, @dangerousbeans, @RegiusK, @agrcrobles, @UnayKing, @masato25, @Webmoss, @jipings, @hhstore, @berkkirtay, @henriquechagasg, @x7chan, @thomasmodeneis, @vpodolyan, @dongsam, @sumdoll, @NextZeus, @stvndf, @LemUhuru, @JingyuZ, @CyndieKamau, @DominikGithub, @dzincolorado, @xcitic, @RaghavaJagannatham, @NukeManDan, @RyanZurrin, @amolgd1, @sbmsr, @lalalune, @Colt-M1873, @shiqimei, @anthonypreza, @larbisahli, @anizioQ, @Durantdzr, @fmunoz92, @lucasmls, @rickbatka, @nelix, @andrew-atkinson, @rjkz808, @giftedchen, @turanzv, @kkpsiren, @Assaneworld, @jvaladasLimitinit, @karlosmid, @greatbsky, @insurshawn, @richardsmet, @FuriouslyCurious, @javiermontescarrera, @miajhaochen, @ntxinh, @ERIKIEERIKOH, @ik5, @kahiga254, @Hokore-Dev, @chaintesting, @Eustatiu, @georgkreimer, @xuguangyuansh, @rodalbert, @cauchym, @fforbeck, @am-ramona, @louyan, @indiansatoshi, @julio1187, @Kimovic, @lokichoggio, @ultraflowsports, @fluffninja, @bitristan, @ThisIsAreku, @stepcellwolf, @zsrl, @mchalise, @micoolee, @jijunpeng, @chivo912, @zrthxn, @0xmer1in, @AM-77, @BusyLivingBusyDiving, @FedericoGarcia, @Jircs1, @NukeManDan, @caiji00, @Dkdaniz, @YoussefAdebouz, @JamesAngus, @devshansharma, @cinquemb, @srkngeograous, @ehrab-xc, @delianides, @hung-doan, @lopeselio, @harishgadde, @dohaki, @barbarbar338, @williamyang-zzu, @bnyra, @4math2379, @scopolamin, @chxj1992, @Radu-D, @massfords, @mamadoo, @befletcher, @MatthieuScarset, @aturX, @robertg, @shargon, @lleonesouza, @guoxingx, @aoooio, @THUNCHO, @xxkp-22xx, @naveen7252, @ktkization, @JimmyWickets, @Eustatiu, @rickbatka, @amitkot, @unlimitedcoder2, @code4trade, @fbaldassarri, @flwmholtz, @xaviarias, @crapthings, @Nero51908, @Bharadwaj1234567890, @HubnesterRising, @paraskumarop, @AntoAndGar, @Thivieira, @mrunal77, @jkd359, @huage404, @iamhitarth, @KydoDev, @technicallyty
